[project]
name = "target-elasticsearch"
version = "2.1.0"
description = "`target-elasticsearch` is a singer target using the meltano SDK for targets"
authors = [{ name = "DT Mirizzi", email = "dtmirizzi@gmail.com" }]
requires-python = ">=3.9.1,<3.14"
license = "GPL-3.0"
keywords = [
    "elasticsearch",
    "ELT",
    "target",
    "meltano",
    "singer",
]
dependencies = [
    "requests>=2.32.0",
    "singer-sdk>=0.47.0",
    "elasticsearch>=8.14.0,<9",
    "Jinja2>=3.1.2",
    "jsonpath-ng>=1.5.3",
    "python-dateutil>=2.8.2",
    "typing-extensions>=4.4.0",
]

[project.scripts]
target-elasticsearch = "target_elasticsearch.target:TargetElasticsearch.cli"

[dependency-groups]
dev = [
    "pytest>=8.0.0",
    "tox>=4.11.0",
    "flake8>=7.0.0",
    "black>=24.3.0",
    "pydocstyle>=6.3.0",
    "mypy>=1.10.0",
    "isort>=5.13.0",
    "pre-commit>=3.7.0",
    "time-machine>=2.14.0",
    "types-python-dateutil>=2.9.0",
]

[build-system]
build-backend = "hatchling.build"
requires = ["hatchling>=1,<2"]

[tool.isort]
profile = "black"
multi_line_output = 3 # Vertical Hanging Indent
src_paths = "target_elasticsearch"

[tool.black]
line-length = 120
target-version = ['py39']
