ELASTIC_YEARLY_FORMAT = "%Y"
ELASTIC_MONTHLY_FORMAT = "%Y.%m"
ELASTIC_DAILY_FORMAT = "%Y.%m.%d"

SCHEME = "scheme"
HOST = "host"
PORT = "port"
USERNAME = "username"
PASSWORD = "password"
BEARER_TOKEN = "bearer_token"
API_KEY_ID = "api_key_id"
API_KEY = "api_key"
SSL_CA_FILE = "ssl_ca_file"
INDEX_FORMAT = "index_format"
SCHEMA_MAPPING = "schema_mapping"
